[general]
cache-control-headers = false

[advanced]

[[advanced.headers]]
source = "/"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"

[[advanced.headers]]
source = "/index.html"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"

[[advanced.headers]]
source = "/sw.js"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"

[[advanced.headers]]
source = "/manifest.webmanifest"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"

[[advanced.headers]]
source = "/assets/*"
[advanced.headers.headers]
Cache-Control = "public, max-age=31536000, immutable"

[[advanced.headers]]
source = "/workbox-*.js"
[advanced.headers.headers]
Cache-Control = "public, max-age=31536000, immutable"
